// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type AuditLog struct {
	ID        int64
	UserID    sql.NullInt64
	Level     int64
	Message   string
	CreatedAt int64
}

type Condominium struct {
	ID        int64
	Name      string
	Address   string
	CreatedAt int64
	UpdatedAt int64
	CreatedBy sql.NullInt64
	UpdatedBy sql.NullInt64
}

type User struct {
	ID            int64
	CondominiumID sql.NullInt64
	FirstName     string
	LastName      string
	Email         string
	Phone         sql.NullString
	Role          string
	Password      string
	Enabled       bool
	Hidden        bool
	CreatedAt     int64
	UpdatedAt     int64
	CreatedBy     sql.NullInt64
	UpdatedBy     sql.NullInt64
}

type Visit struct {
	ID            string
	CondominiumID int64
	UserID        int64
	VisitorName   string
	MaxUses       int64
	Uses          int64
	ValidFrom     int64
	ValidTo       int64
	CreatedAt     int64
	UpdatedAt     int64
}
